# Generated by Django 4.2.14 on 2024-07-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expiration', models.DateTimeField(blank=True, null=True)),
                ('slug', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=25000)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
