# Generated by Django 4.2.14 on 2024-07-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codestorage',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
