# Generated by Django 4.2.14 on 2024-07-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_codestorage_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codestorage',
            name='slug',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
